name: update-lockfile
on:
  schedule:
    - cron: "0 0 * * 0" # weekly, Sunday midnight
  workflow_dispatch:

jobs:
  lockfile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "chore: update flake.lock"
